import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { AuthProvider } from "@/context/auth.context";
import { InterviewProvider } from "@/context/interview.context"
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} h-full antialiased font-sans`}
    >
      
      <body className="min-h-full flex flex-col bg-black text-white">
        <AuthProvider>
          <InterviewProvider>
            {children}
          </InterviewProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
